(()=>{
  const params=new URL(location.href).searchParams;
  if(params.get('dev')!=='1')return;
  document.documentElement.dataset.developerMode='1';

  const allowedTiers=['auto','full','balanced','constrained','critical'];
  let selected=allowedTiers.includes(params.get('devq'))?params.get('devq'):'auto';
  function decorateLink(a){
    if(!a||!a.matches?.('a[href]'))return;
    const raw=a.getAttribute('href');
    if(!raw||raw.startsWith('#')||raw.startsWith('mailto:')||raw.startsWith('tel:')||raw.startsWith('javascript:'))return;
    try{
      const u=new URL(raw,location.href);
      if(u.origin!==location.origin)return;
      u.searchParams.set('dev','1');
      if(selected!=='auto')u.searchParams.set('devq',selected);else u.searchParams.delete('devq');
      const base=location.pathname.slice(0,location.pathname.lastIndexOf('/')+1);
      a.href=u.pathname.startsWith(base)?u.pathname.slice(base.length)+u.search+u.hash:u.pathname+u.search+u.hash;
    }catch(_){ }
  }
  function carryDev(root=document){
    if(root.matches?.('a[href]'))decorateLink(root);
    root.querySelectorAll?.('a[href]').forEach(decorateLink);
  }
  carryDev();
  // Worlds and level cards are generated by deferred ES modules after this
  // script has already run. Keep developer mode attached to those late links.
  const linkObserver=new MutationObserver(records=>{
    for(const record of records){
      for(const node of record.addedNodes){
        if(node.nodeType===1)carryDev(node);
      }
    }
  });
  linkObserver.observe(document.documentElement,{childList:true,subtree:true});
  // Final guard: decorate an internal link again on the actual tap/click.
  document.addEventListener('pointerdown',e=>decorateLink(e.target.closest?.('a[href]')),{capture:true,passive:true});
  document.addEventListener('click',e=>decorateLink(e.target.closest?.('a[href]')),{capture:true});

  const style=document.createElement('style');
  style.textContent=`
    #cqDevFab{position:fixed;z-index:9998;right:12px;bottom:12px;min-width:54px;min-height:44px;border-radius:999px;border:1px solid rgba(105,225,255,.42);background:rgba(3,15,22,.92);color:#80efff;font:800 12px/1 system-ui,sans-serif;letter-spacing:.10em;padding:0 14px;box-shadow:0 8px 30px rgba(0,0,0,.38)}
    #cqDevPanel{position:fixed;z-index:9999;right:10px;bottom:64px;width:min(330px,calc(100vw - 20px));padding:14px;border:1px solid rgba(105,225,255,.35);border-radius:20px;background:rgba(3,13,20,.97);box-shadow:0 18px 60px rgba(0,0,0,.55);color:#eafcff;font-family:system-ui,sans-serif;display:none}
    #cqDevPanel.open{display:block} #cqDevPanel h2{margin:0 0 4px;font-size:15px;letter-spacing:.07em} #cqDevPanel p{margin:0 0 11px;color:#8fb8c7;font-size:11px;line-height:1.35}
    #cqDevChoices{display:grid;grid-template-columns:1fr 1fr;gap:7px} #cqDevChoices button{min-height:42px;border-radius:13px;border:1px solid rgba(115,219,245,.18);background:#071a23;color:#cdebf4;font:750 11px system-ui,sans-serif;padding:7px}
    #cqDevChoices button[data-tier="auto"]{grid-column:1/-1} #cqDevChoices button.active{border-color:#67e4ff;background:#0d3542;color:#fff;box-shadow:inset 0 0 18px rgba(82,224,255,.08)}
    #cqDevReadout{margin-top:10px;padding:9px 10px;border-radius:12px;background:#051117;color:#93bdcb;font:11px/1.45 ui-monospace,monospace} #cqDevReadout strong{color:#f1fcff}
    html[data-developer-mode="1"] body{--cq-dev-mode:1}
  `;
  document.head.appendChild(style);
  const fab=document.createElement('button');fab.id='cqDevFab';fab.type='button';fab.textContent='DEV';fab.setAttribute('aria-label','Open developer quality controls');
  const panel=document.createElement('section');panel.id='cqDevPanel';panel.innerHTML=`<h2>QUALITY OVERRIDE</h2><p>Force the renderer tier on this device. AUTO restores the normal performance governor.</p><div id="cqDevChoices"></div><div id="cqDevReadout">Waiting for renderer…</div>`;
  document.body.append(panel,fab);
  fab.addEventListener('click',()=>panel.classList.toggle('open'));
  const choices=panel.querySelector('#cqDevChoices'),readout=panel.querySelector('#cqDevReadout');
  const tiers=[['auto','AUTO'],['full','FULL'],['balanced','BALANCED'],['constrained','CONSTRAINED'],['critical','CRITICAL']];
  tiers.forEach(([tier,label])=>{const b=document.createElement('button');b.type='button';b.dataset.tier=tier;b.textContent=label;b.addEventListener('click',()=>{selected=tier;const here=new URL(location.href);here.searchParams.set('dev','1');if(tier==='auto')here.searchParams.delete('devq');else here.searchParams.set('devq',tier);history.replaceState(null,'',here);carryDev();const perf=window.__CELLQUATION_PERF__;if(perf?.setDeveloperTier)perf.setDeveloperTier(tier);updateButtons();});choices.appendChild(b)});
  function updateButtons(){choices.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.tier===selected))}
  updateButtons();
  function tick(){
    const perf=window.__CELLQUATION_PERF__;
    if(perf?.state){
      if(perf.setDeveloperTier&&perf.state.developerOverride!==selected)perf.setDeveloperTier(selected);
      const s=perf.state;
      readout.innerHTML=`<strong>${String(s.tier).toUpperCase()}</strong> · override ${String(s.developerOverride||'auto').toUpperCase()}<br>edge ${Number(s.pixelRatioCap||1).toFixed(2)}x · detail ${Math.round(Number(s.renderDetail||1)*100)}%<br>${Number(s.fps||0).toFixed(0)} FPS · jank ${Math.round(Number(s.jank||0)*100)}%`;
    }else readout.textContent='No active game renderer on this screen.';
    requestAnimationFrame(tick);
  }
  requestAnimationFrame(tick);
})();
